<?php

use Drupal\Core\Database\Database;
use Drupal\node\Entity\Node;
use Drupal\user\Entity\User;

/**
 * Implements hook_theme().
 */

function fichaje_module_theme($existing, $type, $theme, $path) {
  return array(

    'empresas_fichar' => array(
      'variables' => array('results' => array(), 'actual' => '')
    ),
    'warning_fichar' => array(
      'variables' => array('fichaje' => array(), 'error' => '')
    ),
    'no_warning_fichar' => array(
    ),
    'result_fichar' => array(
      'variables' => array('results' => array())
    ),
    'usuario_fichajes' => array(
      'variables' => array('results' => array(array(array())), 'buttons' => array(), 'route' => '', 'date' => '', 'isWeek' => '')
    ),
    'admin_partes' => array(
      'variables' => array('users' => array(), 'date' => '', 'names' => array(), 'userName' => '')
    ),
  );
}

function fichaje_module_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'fichaje_module/fichaje_module_css';
}

/**
 * Implements hook_cron().
 */
function fichaje_module_cron()
{
  $connection = Database::getConnection();
  $queryService = \Drupal::service('fichaje_module.query_service');

  $usersIds = $queryService->queryUsersIds($connection);
  foreach ($usersIds as $userId) {

    $user = User::load($userId);
    $last_fichaje = $queryService->queryLastFichaje($connection, $user);

    if ($last_fichaje['type'] === 'Entrada') {

      $fichaje = Node::load($last_fichaje['id']);
      $fichaje->set('field_time_diff_mark', date('Y-m-d\TH:i:s'));
      $fichaje->save();
    }
  }
}
